### ISSUE TITLE
discussion about kotlin

### ISSUE THREAD

**Issue by takov751** [KonradIT/CamControl#10]
just wanted to ask what made you change to kotlin. To be honest i've not heard about this language,goes without saying it does look more straightforward than java. just interested in your opinion.

**Comment by KonradIT** [comment]
I want to learn Kotlin and switch away from Java.

**Comment by takov751** [comment]
Fair enought. I will be stay tuned :D if you have any alpha release just let me know @KonradIT . Thank your for your time answering.
